import "@/styles/globals.css";
import { AnimatePresence, motion } from "framer-motion";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useRouter } from "next/router";

const framerVariants = {
  out: {
    opacity: 0,
    y: 120,
    transition: {
      duration: 0.4,
    },
  },
  in: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.4,
      delay: 0.2,
    },
  },
};

const App = ({ Component, pageProps }: AppProps) => {
  const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>Currency Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence initial={false} mode="wait">
        <motion.div
          key={asPath}
          variants={framerVariants}
          animate="in"
          initial="out"
          exit="out"
        >
          <main>
            <Component {...pageProps} />
          </main>
        </motion.div>
      </AnimatePresence>
    </>
  );
};

export default App;
